[package]
name = "chess-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
useful_shit = { path = "../useful_shit" }
serde_json = "1.0.67"
serde = "1.0.130"